language: python
python:
  - "3.7"
install:
  - virtualenv env --python=python3
  - source env/bin/activate
  - pip install -r requirements.txt
script:
  - pylint *.py && pytest --cov
after_success:
  - codecov
